
#-------------------------------------------------------------------------------
# Maintainer:   jeffskinnerbox@yahoo.com / www.jeffskinnerbox.me
# Version:      1.0.0
#
# USAGE
#	To build the executable and flash the device
#		make
#		make all
#
#	To build the executable
#	    make build
#
#	To flash the device
#	    make upload
#
#	makefile syntax
#	    = set the varialbe
#	    ?= set the variable only if it's not set/doesn't have a value
#	    := set variable as the output an executed shell script
#	    += is used for appending more text to variables
#
#  SOURCES
#
#  DOCUMENTATION
#-------------------------------------------------------------------------------


all: ;

build: ;

upload: ;

erase: ;

size: ;

clean: ;

