#!/usr/bin/expect -f

# grab the arguments off the command-line of this script
set timeout 5;                # timeout after 5 seconds if you get no dialog
set ip [lindex $argv 0];      # grab first argument
set port [lindex $argv 1];    # grab second argument

# begin your interaction
spawn telnet $ip $port;       # startup telnet
expect "\'^]\'.";             # wait for the characters "'^]'."
send "R\r";                   # send 'R' to request reboot

# let the connection drop
interact

